import { v4 as uuidv4 } from 'uuid';
export const navList = [
    {id: '', title: 'Главная'},
    {id: 'catalog', title: 'Каталог'},
    {id: 'aboutUs', title: 'О нас'},
    {id: 'action', title: 'Акция'},
    {id: 'order', title: 'Заказать'},
    {id:'reviews', title:'Отзывы'},
    {id: 'contacts', title: 'Контакты'},
    //{id: 'basket', title: 'Корзина'},
];
export const goodsList = [
    {id: uuidv4(),
    title:'Липовый мёд',
    poster:'../../../../img/goodLindenHoney.png',
    subtitle:'Липовый мед является одним из самых популярных и самых полезных сортов мёда',
    price: 1090},
    {id: uuidv4(),
        title:'Таёжный мёд',
        poster:'../../../../img/goodsTaigaHoney.jpg',
        subtitle:'Таежный дягилевый мед — один из самых высококачественных сортов мёда',
        price: 1100 },
    {id: uuidv4(),
        title:'Мёд в сотах',
        poster:'../../../../img/goodsHoneyComb.jpg',
        subtitle:'Мед в сотах - одно из природных средств, служит одновременно лекарством и лакомством',
        price: 390},
    {id: uuidv4(),
        title:'Лесной василёк мёд',
        poster:'../../../../img/goodForestHoney.png',
        subtitle:'Среди разнотравных сортов меда большое место занимает лесной мед',
        price: 890},
    {id: uuidv4(),
        title:'Прополисный мёд',
        poster:'../../../../img/goodPropolisHoney.png',
        subtitle:'Сильным общеукрепляющим и лечебным средством считается мёд с добавлением прополиса',
        price: 690},
    {id: uuidv4(),
        title:'Цветочный мед',
        poster:'../../../../img/goodFlowerHoney.png',
        subtitle:'Липовый мед является одним из самых популярных и самых полезных сортов мёда',
        price: 790}
]
